### ISSUE TITLE
Create Profile view

### ISSUE THREAD

**Issue by tmorris42** [fyusuf-a/ft_transcendence#103]
The view should be able to take a specific user as a parameter so that it can show either the logged in user OR another user

https://github.com/fyusuf-a/ft_transcendence/wiki/View:-profile

**Comment by tmorris42** [comment]
I hadn't realized that @fyusuf-a was working on something along these lines, but hopefully the two of you can communicate to avoid duplicate work

**Comment by N-4-Nina** [comment]
Yes I meant to ask him directly, as I don't know if it was for exclusively for the demonstration or not

**Comment by fyusuf-a** [comment]
Yes, we talked and agreed that I should push #109 to serve as a basis for future work.
