### ISSUE TITLE
Should we modify Actions to test merged code instead of only the branch code?

### ISSUE THREAD

**Issue by tmorris42** [fyusuf-a/ft_transcendence#121]
Currently the automatic tests are run on the branch, which means that if the branch is not up-to-date with master, the tests are not being run on the code that would be deployed.

We can require the code to be up-to-date before merging, which seems like good practice. But it could also result in situations where a reviewer is having to approve the same code multiple times (due to rebasing).

I think it would be a good idea to look into how this problem is handled in larger projects, and see if we can implement something to solve this. However, this might be time consuming to research and set up, and we have other priorities.

Does anyone have thoughts or knowledge about this issue?

**Comment by fyusuf-a** [comment]
@tmorris42, are you ok to close this after the changes in the reviewing process (no additional review if code is pushed again and tests set to run with a version of the branch up to date with `master`)?
