### ISSUE TITLE
Update TypeORM version

### ISSUE THREAD

**Issue by tmorris42** [fyusuf-a/ft_transcendence#133]
nest/typeorm released version 9.0.0 which uses `typeorm v0.3.x`, previously it was using an outdated `v0.2.x`. We have to use the latest stable version of all libraries and frameworks, so we will have to update our nest/typeorm and TypeORM versions.

 I think there were some changes in the TypeORM API. We may have to be careful when we make the switch.

**Comment by tmorris42** [comment]
Useful: [Breaking Changes](https://typeorm.io/changelog#breaking-changes-1)

**Comment by tmorris42** [comment]
This looks very promising with regards to making paginated responses easier to set up in the future: [Find Options](https://typeorm.io/find-options#basic-options)

**Comment by tmorris42** [comment]
@fyusuf-a I've figured out most of the conflicts except pagination. Should I work on that, too, or would you like to look at it since you set up the initial pagination?

**Comment by fyusuf-a** [comment]
I would be happy to let you do it if you feel like it :)
