### ISSUE TITLE
All services should use the same repository function for the `findOne` service

### ISSUE THREAD

**Issue by tmorris42** [fyusuf-a/ft_transcendence#147]
Right now, some services uses `findOne`/`findOneBy` and some use `findOneOrFail`/`findOneByOrFail`. This should be uniform across all services. We just need to decide which is better.

I prefer the `OrFail` option (I would have used it from the start, if I had known about it), but it is open for debate.

**Comment by N-4-Nina** [comment]
I personally prefer OrFail as well, I was actually in the process of using it to solve #146. I feel like if we have to throw a custom exception every time findOne/By returns undefined we might as well use OrFail; it feels both safer, more concise and more convenient to me.

**Comment by tmorris42** [comment]
I agree. Since you're using OrFail to solve #146, would you be willing to assign this issue and make sure that all of the services match?
