### ISSUE TITLE
friendships needs an "accept" and "reject" route

### ISSUE THREAD

**Issue by N-4-Nina** [fyusuf-a/ft_transcendence#156]
It should change the status of the friendship or delete it.
It should also, when accepted, generate the private channel.

**Comment by tmorris42** [comment]
This is a great idea 👍 

However, for the direct channel, I think that users need to be able to message _any_ user, not just their friends. So it might be better to create those on demand somehow

**Comment by N-4-Nina** [comment]
good point, then it's probably better to create it on the first DM between two users.

**Comment by N-4-Nina** [comment]
But now I wonder, what would an accept/decline route bring over using the update/delete ones ? I guess the update one is too permissive and should actually not be exposed, but still I wonder

**Comment by N-4-Nina** [comment]
Closing this issue as it is now implemented
