### ISSUE TITLE
backend: `/memberships/{id}` does not return 404 on non-existant {id}

### ISSUE THREAD

**Issue by fyusuf-a** [fyusuf-a/ft_transcendence#17]
If a user is put in a channel with a `POST` to `/memberships`, its role cannot be upgraded without a `DELETE` on this route and an additional `POST`. It should be possible to do it with only one HTTP request.

**Comment by fyusuf-a** [comment]
You are right. I have a question: what is the `id` used in `GET` `/memberships/{id}`? Is that the `membershipId`? I have now 2 rows in my `membership` table and the following strange behavior: I get the first row for any `{id}` that is not the second row's one.

**Comment by tmorris42** [comment]
That sounds like a bug. It should indeed be the membershipId
