### ISSUE TITLE
backend: add a way to get messages from a channel in bulk

### ISSUE THREAD

**Issue by fyusuf-a** [fyusuf-a/ft_transcendence#19]
Currently, the route `/messages` allows one to fetch with `GET` the messages by (channel, sender). Maybe it will be useful to enable a bulk retrieve of all the messages in a channel to let the front display them without multiplying requests (e.g. if a channel has, let us suppose, a 100 users).

**Comment by tmorris42** [comment]
You should be able to get all the messages in a channel by only sending a channel parameter with the requests
ex: `/messages?channel=1`

**Comment by fyusuf-a** [comment]
Yes! I thought both parameters were required but none is.
