### ISSUE TITLE
backend: db: create User/Chat database models

### ISSUE THREAD

**Issue by tmorris42** [fyusuf-a/ft_transcendence#2]
Create the required database models in NestJS using TypeORM and the PostgreSQL database

## Users
- Id: `number` `PRIMARY KEY`
- Identity: `string` `UNIQUE`  --> Acquired thru 42API
- Username: `string`
- Avatar: `image`
- Wins: `number`
- Losses: `number`
- Rating: `number`
- Friends:  `User` `FOREIGN KEY: ManyToMany`
- Blocked:  `User` `FOREIGN KEY: ManyToMany`

## Message
- Id: `number` `PRIMARY KEY`
- Contents: `string`
- Sender: `User` `FOREIGN KEY: ManyToOne` 
- Channel:  `Channel` `FOREIGN KEY: ManyToOne`

## Channel/Chatroom
- Id: `number` `PRIMARY KEY`
- Name: `string` `UNIQUE`
- Type: **enum**[`'public'`, `'private'`, `'password-protected'`]
- Messages: `Message` `FOREIGN KEY: OneToMany`
- Password: `string (hashed)` `OPTIONAL`
- Karma: `Karma` `FOREIGN KEY: OneToMany`

## Membership
- Id: `number` `PRIMARY KEY`
- Channel: `Channel` `FOREIGN KEY: ManyToOne`
- User: `User` `FOREIGN KEY: ManyToOne`
- Role: **enum**[`'participant'`, `'admin'`, `'owner'`]

## Karma
- Id: `number` `PRIMARY KEY`
- Channel: `Channel` `FOREIGN KEY: ManyToOne`
- User: `User` `FOREIGN KEY: ManyToOne`
- Start Time: `datetime`
- End Time: `datetime`
- Type: **enum**[`'ban'`, `'mute'`]

**Comment by fyusuf-a** [comment]
It looks good! Maybe we could remove the Recipients from the Message table as we have the Channel. We may also use an ELO score (and get a level by dividing it by 100).

**Comment by tmorris42** [comment]
Good point. I removed Recipients from the Message table.

I also renamed level to Rating where we can store each User's ELO.
