### ISSUE TITLE
fix: Entities with ManyToOne relations should 'CASCADE' onDelete

### ISSUE THREAD

**Issue by tmorris42** [fyusuf-a/ft_transcendence#205]
```suggestion
  @ManyToOne(() => Entity, { onDelete: 'CASCADE' })
```

This will make it so that the dependent entity will be deleted when the related entity is delete. For example, if a channel is deleted then all memberships on that channel would be deleted as well (because they are now meaningless)

**Comment by N-4-Nina** [comment]
#206 was merged, closing this
