### ISSUE TITLE
actual achievements

### ISSUE THREAD

**Issue by N-4-Nina** [fyusuf-a/ft_transcendence#224]
the achievements system should work but we do not have any defined. We should decide what achievements we want and initialize them at build. @Mel-louie and I think it would be better to only have game-related achievements (number of played games, wins, etc..) so we can keep it very simple and do a single check/update at the end of every match.

**Comment by fyusuf-a** [comment]
Some easy ideas:
- first friend
- first game
- wins 5 games
- plays 10 games
- wins with no point for the adversary
