### ISSUE TITLE
Feat: the users need to have a status (online, offline, in a game, and other?)

### ISSUE THREAD

**Issue by Mel-louie** [fyusuf-a/ft_transcendence#234]
The users need to have a status. It should be display on the Friends list (Profile page)

**Comment by tmorris42** [comment]
I think the easiest way to handle this would be to add a `status` column to each user, which could be updated based on socket connections. 

If that sounds good to you, then I can add this to the backend once the changes to the game have merged.

I'm thinking it could be an enum with the following values:
- [ ] In-Game (if connected to a socket and in an active game)
- [ ] Online (if connected to a socket)
- [ ] Offline (default / null)

and possibly:
- [ ] Spectating (if connected and spectating an active game)

But let me know if there are any other things that you'd like to see

**Comment by N-4-Nina** [comment]
When you talk about socket, do you think of a new gateway just for handling the status, or do you think the chat socket and the game socket could do the trick ? I guess my question is: is the user always connected to the chat socket when using the webapp or only when actually using the chat ?

**Comment by tmorris42** [comment]
I think the existing gateways could do the trick. Right now the chat connects the first time the user goes to the chat, but we could adjust that so that the user automatically connects when signing in

**Comment by N-4-Nina** [comment]
Do you mind if i give it a try ?

**Comment by tmorris42** [comment]
Sure, go for it! You should be able to do the online/offline right away with the ChatGateway, and hopefully the game will be merged soon and the in-game/spectating could be added at that point.

There are handlers already in the ChatGateway to authenticate a socket (at which point we know which user they are and we could update the status to online), and a handler for when a socket disconnects (becomes offline).

**Comment by fyusuf-a** [comment]
I think that a new socket gateway should be created. It should always be connected to in the frontend and would inform the user of new friend requests, blocks, achievements, etc. (sort of a general purpose gateway).

**Comment by N-4-Nina** [comment]
Okay then I'm going to start over. I have to say I wanted to ask the question during today's meeting. As much as I'd like to only use the existing ones, I think you're right. Or maybe it depends on whether notifications are a mandatory part of the subject ?
