### ISSUE TITLE
feat: 2-factor authentication

### ISSUE THREAD

**Issue by tmorris42** [fyusuf-a/ft_transcendence#46]
Add 2-factor authentication using `Google Authenticator`

**Comment by fyusuf-a** [comment]
Note : remember to change the environment of the GitHub actions. Set `DISABLE_AUTHENTICATION` to `false`.

**Comment by tmorris42** [comment]
@fyusuf-a should this be closed now that #227 is merged, or do the GitHub actions still need to be updated first?

**Comment by fyusuf-a** [comment]
I have created an issue for the tests: #249 . Indeed, I am closing this as #227 implements this issue.
