### ISSUE TITLE
fix(api): make controllers return ResponseDtos

### ISSUE THREAD

**Issue by tmorris42** [fyusuf-a/ft_transcendence#49]
Each controller should return a `Response*Dto` instead of a complete `*Dto`

**Comment by N-4-Nina** [comment]
I just checked and I think we are up to date with that. The only one I saw was the achievement's findById, but the only difference between the dto and the responsedto is the id, which must be known by the client when calling findbyid, so this is not an issue worth a pr at this point, i'm closing it.
