### ISSUE TITLE
bug(frontend): error 404 on page refresh

### ISSUE THREAD

**Issue by Mel-louie** [fyusuf-a/ft_transcendence#69]
When reload on a route, a 404 occurs.
There is no problem the first time the page is loaded, nor when "/" is reloaded.
The problem seems to come from Vue Router and/or the Nginx config:

- https://stackoverflow.com/questions/36399319/vue-router-return-404-when-revisit-to-the-url

**Comment by Mel-louie** [comment]
I read the link you posted, it is very clear, thank you
I think I can tackle it, it will allow me to put me back dockerfile and nginx

**Comment by tmorris42** [comment]
PR #74 fixes this issue
