### ISSUE TITLE
Can we remove the console.log from Blocks.service.create now that the block service is functional?

### ISSUE THREAD

**Issue by tmorris42** [fyusuf-a/ft_transcendence#97]
There is a `console.log` at `line 34` in `blocks.service.ts` which is showing up in the testing output. Can it be removed?

If it is still useful, then it is not a big deal. But if it is no longer needed, then removing it would help make the logs more readable.

**Comment by N-4-Nina** [comment]
Sorry I missed this one, but maybe if @fyusuf-a is willing to change block.service in the context of #104 he could delete it as well; if not I'll do it asap.

**Comment by tmorris42** [comment]
It is no problem, I just made an issue to make a note of it.

And that sounds good, we can see what happens with #104 and then fix this after if necessary

**Comment by tmorris42** [comment]
#104 was closed, and this doesn't seem to be handled in #109. But it is an easy fix, so I'll just make a PR for it quickly
